### ISSUE TITLE
Count is off for location based tags

### ISSUE THREAD

**Issue by psilospore** [umihico/thumbnailed-portfolio-websites#28]
If I go to All Locations and click on Maryland (4) I only see 2 results while 4 is listed

**Comment by umihico** [comment]
Thank you for letting me know! It is because one of their portfolio url is invalid. I probably change behavior to count only valid ones. I added  new page [here](https://umihico.github.io/thumbnailed-portfolio-websites/database.html ) to check all status.

**Comment by umihico** [comment]
fixed! thanks again
