### ISSUE TITLE
You're doing something wrong

### ISSUE THREAD

**Issue by ndsc2019** [umihico/thumbnailed-portfolio-websites#35]
Don't do such collections of other projects without prior permission from their respective authors. Be aware of legal issues.

Many publications (books, etc.) are accessible publicly. However, that does not mean you can list their content without permission. The same applies to websites.

**Comment by umihico** [comment]
Thank you for your comment.

There is already same issue [here] (https://github.com/umihico/thumbnailed-portfolio-websites/issues/31)

I close this but I'd like to hear your opinion more there.
