### ISSUE TITLE
crawler stopped?

### ISSUE THREAD

**Issue by 7ma7X** [umihico/thumbnailed-portfolio-websites#36]
I like the idea of collecting everybody's portfolio, though it may be somewhat controversial lol

I checked out [recent updates](http://umihi.co/thumbnailed-portfolio-websites/recently_updated0001.html) and found out the archive has not been updated since 2019-02-04. Did you stop this project? If not, it'd be better to make sure whether the crawler works fine.

**Comment by umihico** [comment]
Sorry! I just erased my EC2 environment recently with some trouble and that's way I didn't. I'll do it soon and close this when everything get refreshed! Your issuing motivated me a lot. Thank you!

**Comment by umihico** [comment]
Done! I confirmed yours is crawled.
(sister website is still ongoing)
