### ISSUE TITLE
Best repo i found today on github

### ISSUE THREAD

**Issue by anuraghazra** [umihico/thumbnailed-portfolio-websites#38]
## I just loved it :heart:

@umihico starred my portfolio today and i thought i should look into your github profile and found this repo. 

![Capture](https://user-images.githubusercontent.com/35374649/54081444-1cf53f00-432b-11e9-98b2-788e7309a6d1.PNG)

And after reading you status i instantly fall in love with this. its very unique and creative. :fireworks: 

![Capture2](https://user-images.githubusercontent.com/35374649/54081481-73627d80-432b-11e9-835f-e95633d30f49.PNG)

Thanks for this awesome repo. i shared this with all my friends.

**Comment by umihico** [comment]
Thank you for your great comment! I'm happy to hear that.

**Comment by anuraghazra** [comment]
:heart:
