### ISSUE TITLE
UX/UI Help?

### ISSUE THREAD

**Issue by dk4jo3** [umihico/thumbnailed-portfolio-websites#39]
Hey, 

saw your project and found it very interesting, would you like some ux/ui help to improve the site? I can possibly provide some html/css helps as well depends on the complexity. 

email is "my github handle"@gmail.com 

-kc

**Comment by umihico** [comment]
hello @dk4jo3 
Thank you for your great suggestion! I'd love to apply your UX/UI change.

Now I'm using python renderer Flask & FrozenFlask on gh-pages but I think I wanna use laravel PHP on AWS lambda one day maybe. You can suggest anything and I'm down to change with it!

**Comment by dk4jo3** [comment]
Great so I will come up with some mockups that better organize the information on the site and discuss with you before I make any changes. 

Do you have any data on the click-through rate of the links (eg. repo link, username link, star/fork,  locations)? there are a lot of links on the page atm and I think we can prioritize some over others.

**Comment by umihico** [comment]
Sounds exiting.

No sir, it's just plain github pages and there is no way to count currently. Maybe I can try putting some script and start counting? I'll comment about it again in a few days.

**Comment by umihico** [comment]
Sorry for late replay.
I added Google Analytics and this is the result for a latest few days.
https://docs.google.com/spreadsheets/d/1aC5_izkIEaPjJp0Vddz0VBrbvDkAZa3Bf_BVOyHcahI/edit?usp=sharing

My website is not popular at all yet but if I keep updating, I guess there'll be more visitors. It was good to know that database.html and US pages are popular.

You can wait till this stat increase more or you can start now if you code for your fun ;)

**Comment by dk4jo3** [comment]
I made a mockup for the site. organized some infos on the site and clean up the UI. https://imgur.com/a/GZPEB3f lmk what you think. I will start making some changes based on this design next week. might need a bit help about the color bar interaction part but we will see.

**Comment by umihico** [comment]
wow it is cool design, especially the dynamic skillset displaying when mouseover!

It seems I have to implement dynamic searchable engine. I knew it's necessary function and I think it's the time to start moving from gh-page to laravel. Do I need to work something else?

**Comment by umihico** [comment]
Merged your pull request.
Thank you very much @dk4jo3

**Comment by umihico** [comment]
@dk4jo3 
https://portfoliohub.umihi.co/
I finally made it! I created basics inspired by your design. It was long journey. I'll keep updating

**Comment by dk4jo3** [comment]
Woo! looking good. let me know if you need any help.
